services:
  # !! Backend services
  backend-users-api:
    image: morineth/taxarific-backend-user-api:latest
    ports:
      - "8080:8080"
    # restart: on-failure
    networks:
      - taxarific
  email-service:
    image: morineth/taxarific-backend-email-service:latest
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - kafka
      - zookeeper
    networks:
      - taxarific

  # !! Outside services
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - kafka_data:/bitnami
    depends_on:
      - zookeeper
    restart: on-failure
    networks:
      - taxarific
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zoo_data:/bitnami
    restart: on-failure
    networks:
      - taxarific

  # !! Frontend service
  frontend-service:
    image: morineth/taxarific-frontend:latest
    ports:
      - "80:80"
    restart: on-failure
    networks:
      - taxarific
volumes:
  kafka_data: {}
  zoo_data: {}
networks:
  taxarific:
    driver: bridge
