services:
  backend-users-api:
    build: ./BackEndService/users_api
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - taxarific
  # backend-tax-api:
  #   build: ./BackEndService/tax_api
  #   ports:
  #     - "8081"
  #   restart: on-failure
  #   networks:
  #     - taxarific
  frontend-service:
    build: ./FrontEndService
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      - taxarific
networks:
  taxarific:
    driver: bridge
