# syntax=docker/dockerfile:1

FROM golang:latest

# Set destination for COP
WORKDIR /frontend

# Download Go modules
# COPY go.mod go.sum ./
COPY go.mod ./
RUN go mod download

# Copy code
COPY . .

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /frontend-api

EXPOSE 8080

# Run
CMD [ "/frontend-api" ]