# syntax=docker/dockerfile:1

FROM golang:latest

# Set destination for COP
WORKDIR /api

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy code
COPY . .

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /frontend-api

EXPOSE 3000

# Run
CMD [ "/frontend-api" ]