version: "3"
services:
  backend-users-api:
    build: ./users_api
    ports:
      - "8080"
    depends_on:
      - database
    restart: on-failure
    networks:
      - taxarific 

  # DataBase
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    restart: on-failure
    networks:
      - taxarific 
  # MongoDB Exporter
  dbexporter:
    image: bitnami/mongodb-exporter:latest
    environment:
        - MONGODB_URI=mongodb://monitor:reader@database:27017/?authSource=Games
    ports:
        - "9216"
    depends_on:
        - database
    restart: on-failure
    networks:
        - taxarific 
        

volumes:
  db_data: {}
networks:
  taxarific:
    driver: bridge
