// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package models

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// Admin defines model for Admin.
type Admin struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Email     openapi_types.Email `json:"email"`
	Id        primitive.ObjectID  `bson:"_id,omitempty" json:"id"`
	Name      string              `json:"name"`
	Password  string              `json:"omitempty"`
	UpdatedAt *time.Time          `json:"updated_at,omitempty"`
}

// Case defines model for Case.
type Case struct {
	CaseDescription *string             `json:"case_description,omitempty"`
	CaseId          *openapi_types.UUID `json:"case_id,omitempty"`
	CaseStatus      *string             `json:"case_status,omitempty"`
	CreatedAt       *time.Time          `json:"created_at,omitempty"`
	UpdatedAt       *time.Time          `json:"updated_at,omitempty"`
	UserId          openapi_types.UUID  `json:"user_id"`
}

// Employee defines model for Employee.
type Employee struct {
	Cases     *[]Case             `json:"cases,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Email     openapi_types.Email `json:"email"`
	Id        primitive.ObjectID  `bson:"_id,omitempty" json:"id"`
	Name      string              `json:"name"`
	Password  string              `json:"omitempty"`
	UpdatedAt *time.Time          `json:"updated_at,omitempty"`
}

// User defines model for User.
type User struct {
	Address   *string             `json:"address,omitempty"`
	City      *string             `json:"city,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Email     openapi_types.Email `json:"email"`
	Id        primitive.ObjectID  `bson:"_id,omitempty" json:"id"`
	Name      string              `json:"name"`
	Password  string              `json:"omitempty"`
	Phone     *string             `json:"phone,omitempty"`
	State     *string             `json:"state,omitempty"`
	UpdatedAt *time.Time          `json:"updated_at,omitempty"`
	Zip       *string             `json:"zip,omitempty"`
}

// PostAdminJSONRequestBody defines body for PostAdmin for application/json ContentType.
type PostAdminJSONRequestBody = Admin

// PostAdminEmployeeJSONRequestBody defines body for PostAdminEmployee for application/json ContentType.
type PostAdminEmployeeJSONRequestBody = Employee

// PutEmployeeEmployeeidJSONRequestBody defines body for PutEmployeeEmployeeid for application/json ContentType.
type PutEmployeeEmployeeidJSONRequestBody = Employee

// PostUserJSONRequestBody defines body for PostUser for application/json ContentType.
type PostUserJSONRequestBody = User

// PutUserUseridJSONRequestBody defines body for PutUserUserid for application/json ContentType.
type PutUserUseridJSONRequestBody = User
