// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package models

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// UserWithoutPasswordOrCreatedAt defines model for UserWithoutPasswordOrCreatedAt.
type UserWithoutPasswordOrCreatedAt struct {
	Address *string              `json:"address,omitempty"`
	City    *string              `json:"city,omitempty"`
	Country *string              `json:"country,omitempty"`
	Email   *openapi_types.Email `json:"email,omitempty"`
	Id      *openapi_types.UUID  `json:"id,omitempty"`
	Name    *string              `json:"name,omitempty"`
	Phone   *string              `json:"phone,omitempty"`
	State   *string              `json:"state,omitempty"`
	Zip     *string              `json:"zip,omitempty"`
}

// PutUserIdJSONRequestBody defines body for PutUserId for application/json ContentType.
type PutUserIdJSONRequestBody = UserWithoutPasswordOrCreatedAt
