# syntax=docker/dockerfile:1

FROM golang:latest

# Set destination for COP
WORKDIR /email

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy code
COPY . .

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /gamesemail

EXPOSE 8080

# Run
CMD [ "/gamesemail" ]